/* automatically generated by rust-bindgen 0.71.1 */

pub const OutputFormat_native: OutputFormat = 0;
pub const OutputFormat_bgra: OutputFormat = 1;
pub const OutputFormat_bgra64: OutputFormat = 2;
pub type OutputFormat = ::std::os::raw::c_uint;
unsafe extern "C" {
    #[link_name = "\u{1}_Z10DecodeProciPKc12OutputFormatS0_"]
    pub fn DecodeProc(
        cuDevice: ::std::os::raw::c_int,
        szMediaUri: *const ::std::os::raw::c_char,
        eOutputFormat: OutputFormat,
        szOutFilePath: *const ::std::os::raw::c_char,
    );
}
